apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
      - name: python-backend
        image: myecommerce-python:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: jdbc:mysql://mysql-db:3306/kvsp_paul
        - name: DATABASE_USERNAME
          value: root
        - name: DATABASE_PASSWORD
          value: your_password

